/**
 * Saved Answer Cards API — POST (save) + GET (list own)
 *
 * SECURITY:
 * - isValidOrigin → 403 (CSRF defense in depth)
 * - verifySession → 401 (login-gated; stable user id required)
 * - MOAT GATE: a card can only be saved if its HMAC signature verifies. Since
 *   only the server holds the secret, this proves the card was generated by
 *   VerChem — a forged "VERIFIED" card cannot be persisted.
 * - aiverid_id taken from the session, never the client.
 */

import { NextRequest, NextResponse } from 'next/server'
import { verifySession } from '@/lib/auth/session'
import { isValidOrigin } from '@/lib/auth/origin-check'
import { verifyCardSignature, toSignablePayload } from '@/lib/answer-cards/signature'
import { parseSubmittedCard } from '@/lib/answer-cards/validate-card'
import { createAnswerCard, listAnswerCardsByUser } from '@/lib/supabase/answer-cards'
import { checkRateLimit } from '@/lib/rate-limit'

// Generous per-user daily cap so a valid signed card can't be saved thousands
// of times to bloat the table. (Saving requires a real generate call first.)
const SAVE_LIMIT = { windowMs: 24 * 60 * 60 * 1000, maxRequests: 200 }

export async function POST(request: NextRequest) {
  try {
    if (!isValidOrigin(request)) {
      return NextResponse.json({ error: 'Invalid origin' }, { status: 403 })
    }

    const session = await verifySession()
    if (!session?.userId || session.userId === 'anonymous') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    let body: unknown
    try {
      body = await request.json()
    } catch {
      return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
    }
    if (typeof body !== 'object' || body === null || Array.isArray(body)) {
      return NextResponse.json({ error: 'Body must be a JSON object' }, { status: 400 })
    }

    const record = body as Record<string, unknown>
    const card = parseSubmittedCard(record.card)
    if (!card) {
      return NextResponse.json({ error: 'Invalid or malformed answer card' }, { status: 400 })
    }

    // MOAT GATE — the signature is the trust anchor. Only a card actually signed
    // by this server (its secret) can be saved. Tampering with any signed field
    // breaks the HMAC and is rejected here.
    const authentic = await verifyCardSignature(toSignablePayload(card), card.signature)
    if (!authentic) {
      return NextResponse.json(
        { error: 'Card signature is invalid — only cards generated by VerChem can be saved.' },
        { status: 400 }
      )
    }

    const is_public = typeof record.is_public === 'boolean' ? record.is_public : false

    const rl = checkRateLimit(`answer-card-save:${session.userId}`, SAVE_LIMIT)
    if (!rl.success) {
      return NextResponse.json(
        { error: 'Daily save limit reached. Please try again tomorrow.', retryAfter: rl.retryAfter },
        { status: 429, headers: { 'Retry-After': String(rl.retryAfter ?? 0) } }
      )
    }

    const saved = await createAnswerCard({ aiverid_id: session.userId, card, is_public })
    return NextResponse.json(saved, { status: 201 })
  } catch (err: unknown) {
    console.error('POST /api/answer-cards error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}

export async function GET(_request: NextRequest) {
  try {
    const session = await verifySession()
    if (!session?.userId || session.userId === 'anonymous') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const cards = await listAnswerCardsByUser(session.userId)
    return NextResponse.json(cards)
  } catch (err: unknown) {
    console.error('GET /api/answer-cards error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
