/**
 * Public Verified Answer Card — /verified/[id]
 *
 * The shareable, viral artifact. Anyone (no login) can open a public card.
 * The signature is RE-VERIFIED server-side here; a card whose stored bytes no
 * longer match its signature renders with a TAMPERED banner instead of a
 * VERIFIED badge. Owner identity (aiverid_id) is never read.
 */

import { cache } from 'react'
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import Link from 'next/link'
import { getPublicAnswerCardById } from '@/lib/supabase/answer-cards'
import AnswerCardView from '@/components/answer-cards/AnswerCardView'

export const dynamic = 'force-dynamic'

const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

interface PageProps {
  params: Promise<{ id: string }>
}

// Deduped per request — generateMetadata + the page share one DB read.
const loadPublicCard = cache(async (id: string) => {
  if (!UUID_REGEX.test(id)) return null
  try {
    return await getPublicAnswerCardById(id)
  } catch {
    return null
  }
})

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { id } = await params
  const loaded = await loadPublicCard(id)
  if (!loaded) return { title: 'Verified Answer — VerChem' }

  const q = loaded.card.question.slice(0, 110)
  const desc =
    'A chemistry answer computed by deterministic engines and cryptographically signed by VerChem — not generated by a language model.'
  return {
    title: `${q} — Verified Chemistry Answer | VerChem`,
    description: desc,
    openGraph: { title: q, description: desc, type: 'article' },
    twitter: { card: 'summary', title: q, description: desc },
  }
}

export default async function PublicAnswerCardPage({ params }: PageProps) {
  const { id } = await params
  const loaded = await loadPublicCard(id)
  if (!loaded) notFound()

  const issued = new Date(loaded.created_at).toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-blue-950/20 to-slate-950">
      <section className="relative overflow-hidden pt-16 pb-8">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-500/10 via-transparent to-transparent" />
        <div className="relative mx-auto max-w-3xl px-4 text-center">
          <Link
            href="/tools/verified-answer"
            className="inline-flex items-center gap-2 rounded-full border border-green-500/30 bg-green-500/10 px-4 py-2 text-sm text-green-300 mb-6 transition hover:bg-green-500/20"
          >
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            VerChem Verified Answer
          </Link>
          <p className="text-sm text-slate-400">Shared verified answer · {issued}</p>
        </div>
      </section>

      <section className="pb-20 px-4">
        <div className="mx-auto max-w-3xl">
          <div className="rounded-3xl border border-white/10 bg-gradient-to-br from-slate-900/90 to-slate-900/50 p-6 md:p-8 shadow-2xl backdrop-blur-sm">
            <h1 className="text-xl md:text-2xl font-semibold text-white mb-6">
              Q: {loaded.card.question}
            </h1>
            <AnswerCardView card={loaded.card} signatureValid={loaded.signatureValid} />
          </div>

          {/* CTA: verify chemistry yourself */}
          <div className="mt-8 text-center">
            <p className="text-slate-400 mb-3 text-sm">
              Numbers computed by deterministic engines, not a language model — and signed so they
              can&apos;t be quietly altered.
            </p>
            <Link
              href="/tools/verified-answer"
              className="inline-flex items-center gap-2 rounded-xl border border-blue-500/30 bg-blue-500/10 px-5 py-2.5 text-sm font-medium text-blue-200 transition hover:bg-blue-500/20"
            >
              Ask your own chemistry question
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M13 7l5 5m0 0l-5 5m5-5H6" />
              </svg>
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}
