import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — VerChem',
  description:
    'The terms that govern your use of VerChem — its chemistry tools, accounts, AI Verified Answer Cards, and voluntary donations.',
  alternates: { canonical: 'https://verchem.xyz/terms' },
}

// TODO(พี่จ๊อบ): set the operating legal entity name and the governing-law
// jurisdiction in the "Governing law" section below before this is treated as
// the final binding version. The rest describes the service as actually built.
const EFFECTIVE_DATE = 'May 27, 2026'
const CONTACT_EMAIL = 'verchem.xyz@gmail.com'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-2xl font-bold text-foreground mb-3">{title}</h2>
      <div className="space-y-3 text-secondary-700 dark:text-secondary-300 leading-relaxed">
        {children}
      </div>
    </section>
  )
}

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 via-background to-secondary-50 dark:from-neutral-950 dark:via-neutral-900 dark:to-neutral-950">
      <header className="border-b border-header-border bg-header-bg backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 group">
            <span className="text-xl font-bold bg-gradient-to-r from-primary-600 to-secondary-600 bg-clip-text text-transparent">
              VerChem
            </span>
          </Link>
          <Link
            href="/"
            className="text-secondary-600 hover:text-primary-600 transition-colors font-medium text-sm"
          >
            ← Back to VerChem
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-4xl font-bold text-foreground mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Effective {EFFECTIVE_DATE}</p>

        <Section title="Acceptance of terms">
          <p>
            By accessing or using VerChem (“the service”), you agree to these Terms of
            Service. If you do not agree, please do not use the service.
          </p>
        </Section>

        <Section title="The service">
          <p>
            VerChem provides free chemistry education tools, including calculators, a
            periodic table and compounds database, organic and spectroscopy references, a
            2D structure editor, substructure search, and AI Verified Answer Cards. The
            service is offered for educational and reference purposes.
          </p>
        </Section>

        <Section title="Accounts">
          <p>
            Some features require signing in through AIVerID. You are responsible for
            activity under your account and for keeping your AIVerID credentials secure.
            You must provide accurate information and use the service only as permitted by
            law.
          </p>
        </Section>

        <Section title="Educational & scientific disclaimer">
          <p>
            VerChem’s calculations, data, and guidance are provided for{' '}
            <strong>educational and reference purposes only</strong>. While we validate
            our data against recognized sources (e.g., NIST/IUPAC) and compute results
            with deterministic engines, you remain responsible for independently
            verifying any result before relying on it.
          </p>
          <p>
            VerChem is <strong>not</strong> a substitute for professional judgment, and
            nothing here constitutes safety, medical, legal, regulatory, or professional
            engineering advice. Lab safety and chemical-handling information is general in
            nature — always follow your institution’s procedures and the official Safety
            Data Sheet for any substance.
          </p>
        </Section>

        <Section title="What “Verified” means">
          <p>
            For AI Verified Answer Cards, “Verified” means the numeric result was produced
            by VerChem’s own deterministic calculation engine (not generated by a language
            model) and cryptographically signed. It does <strong>not</strong> guarantee
            the question was interpreted as you intended. For any critical use, confirm the
            inputs and check the result yourself.
          </p>
        </Section>

        <Section title="Acceptable use">
          <ul className="list-disc pl-6 space-y-1">
            <li>Do not misuse, overload, probe, or attempt to disrupt the service.</li>
            <li>Do not attempt to bypass authentication, rate limits, or security controls.</li>
            <li>Do not use the service for unlawful or harmful purposes.</li>
            <li>Do not upload content you do not have the right to share.</li>
          </ul>
        </Section>

        <Section title="Your content">
          <p>
            You retain ownership of content you create (such as drawn molecules). By
            choosing to make an item public (for example, via a share link), you grant us
            permission to store and display it as needed to provide that feature. You may
            delete your content at any time.
          </p>
        </Section>

        <Section title="Donations">
          <p>
            VerChem is free. Donations are entirely voluntary, are processed by Stripe,
            and support continued development. Because no goods or services are exchanged
            for a donation, donations are generally non-refundable except where required
            by law.
          </p>
        </Section>

        <Section title="Intellectual property">
          <p>
            VerChem, its name, design, original content, and software are owned by us or
            our licensors and are protected by applicable law. Open-source components are
            used under their respective licenses.
          </p>
        </Section>

        <Section title="Service provided “as is”">
          <p>
            The service is provided “as is” and “as available,” without warranties of any
            kind, whether express or implied, including fitness for a particular purpose
            and accuracy. To the maximum extent permitted by law, we are not liable for
            any indirect, incidental, or consequential damages arising from your use of —
            or inability to use — the service or its results.
          </p>
        </Section>

        <Section title="Changes & availability">
          <p>
            We may modify, suspend, or discontinue any part of the service, and may update
            these terms from time to time. Material changes will be reflected by updating
            the effective date above. Continued use after changes means you accept the
            updated terms.
          </p>
        </Section>

        <Section title="Governing law">
          <p>
            These Terms are governed by the laws of the jurisdiction in which VerChem is
            operated, without regard to conflict-of-law rules. (The specific operating
            entity and jurisdiction will be stated here.)
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about these terms? Email us at{' '}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary-600 hover:underline">
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </Section>

        <p className="text-sm text-muted-foreground border-t border-border pt-6">
          See also our{' '}
          <Link href="/privacy" className="text-primary-600 hover:underline">
            Privacy Policy
          </Link>
          .
        </p>
      </main>
    </div>
  )
}
