'use client';

import React, { useState, useEffect, useRef } from 'react';
import { ExportManager } from '@/lib/export/export-manager';

interface PrintLayoutProps {
  children: React.ReactNode;
  title?: string;
  subtitle?: string;
  showHeader?: boolean;
  showFooter?: boolean;
  showDate?: boolean;
  customHeader?: React.ReactNode;
  customFooter?: React.ReactNode;
  className?: string;
  printStyles?: string;
}

const DefaultHeader: React.FC<{
  title: string;
  subtitle?: string;
  showDate: boolean;
  printDate: Date;
}> = ({ title, subtitle, showDate, printDate }) => (
  <div className="print-header">
    <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">{title}</h1>
    {subtitle && (
      <p className="text-lg text-gray-600 dark:text-gray-400">{subtitle}</p>
    )}
    {showDate && (
      <p className="text-sm text-gray-500 dark:text-gray-500">
        Generated on {printDate.toLocaleDateString()} at {printDate.toLocaleTimeString()}
      </p>
    )}
  </div>
);

const DefaultFooter: React.FC = () => (
  <div className="print-footer">
    <div className="flex justify-between items-center">
      <span>Generated by VerChem - Chemistry Tools</span>
      <span>Page 1</span>
    </div>
  </div>
);

const PrintLayout: React.FC<PrintLayoutProps> = ({
  children,
  title = 'VerChem Export',
  subtitle,
  showHeader = true,
  showFooter = true,
  showDate = true,
  customHeader,
  customFooter,
  className = '',
  printStyles = ''
}) => {
  const [isPrintMode, setIsPrintMode] = useState(false);
  const [printDate] = useState(new Date());
  const contentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (isPrintMode) {
      // Add print-specific styles
      const style = document.createElement('style');
      style.textContent = `
        @media print {
          body * {
            visibility: hidden;
          }
          
          .print-layout-container, .print-layout-container * {
            visibility: visible;
          }
          
          .print-layout-container {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
          }
          
          .print-header {
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
            margin-bottom: 20px;
          }
          
          .print-footer {
            border-top: 1px solid #ccc;
            padding-top: 10px;
            margin-top: 20px;
            font-size: 12px;
            color: #666;
          }
          
          .print-content {
            page-break-inside: avoid;
          }
          
          .no-print {
            display: none !important;
          }
          
          ${printStyles}
        }
      `;
      document.head.appendChild(style);

      // Trigger print after a short delay to ensure styles are applied
      setTimeout(() => {
        window.print();
        setIsPrintMode(false);
      }, 100);

      return () => {
        document.head.removeChild(style);
      };
    }
  }, [isPrintMode, printStyles]);

  const handlePrint = () => {
    setIsPrintMode(true);
  };

  const handleExportPDF = async () => {
    if (contentRef.current) {
      try {
        await ExportManager.exportElement(contentRef.current, {
          format: 'pdf',
          quality: 'high',
          filename: title.replace(/\s+/g, '_'),
          includeTimestamp: true
        });
      } catch (error) {
        console.error('PDF export failed:', error);
      }
    }
  };

  const handleExportImage = async (format: 'png' | 'jpeg') => {
    if (contentRef.current) {
      try {
        await ExportManager.exportElement(contentRef.current, {
          format,
          quality: 'high',
          filename: title.replace(/\s+/g, '_'),
          includeTimestamp: true
        });
      } catch (error) {
        console.error('Image export failed:', error);
      }
    }
  };

  return (
    <div className={`print-layout-container ${isPrintMode ? 'print-mode' : ''} ${className}`}>
      {/* Print/Export Controls */}
      {!isPrintMode && (
        <div className="no-print mb-4 flex flex-wrap gap-2">
          <button
            onClick={handlePrint}
            className="inline-flex items-center px-3 py-1.5 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-md transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
          >
            <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            Print
          </button>

          <div className="relative group">
            <button className="inline-flex items-center px-3 py-1.5 text-sm font-medium text-gray-700 bg-white border border-gray-300 hover:bg-gray-50 rounded-md transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2">
              <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Export
            </button>
            
            <div className="absolute top-full left-0 mt-1 w-48 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-600 rounded-md shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all z-10">
              <div className="py-1">
                <button
                  onClick={handleExportPDF}
                  className="w-full text-left px-4 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
                >
                  Export as PDF
                </button>
                <button
                  onClick={() => handleExportImage('png')}
                  className="w-full text-left px-4 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
                >
                  Export as PNG
                </button>
                <button
                  onClick={() => handleExportImage('jpeg')}
                  className="w-full text-left px-4 py-2 text-sm text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
                >
                  Export as JPEG
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Main Content */}
      <div ref={contentRef} className="print-content bg-white dark:bg-gray-900">
        {showHeader && (
          <div className="print-header-section">
            {customHeader || (
              <DefaultHeader
                title={title}
                subtitle={subtitle}
                showDate={showDate}
                printDate={printDate}
              />
            )}
          </div>
        )}

        <div className="print-main-content">
          {children}
        </div>

        {showFooter && (
          <div className="print-footer-section">
            {customFooter || <DefaultFooter />}
          </div>
        )}
      </div>

      {/* Print-specific styles */}
      <style jsx>{`
        .print-layout-container {
          max-width: 100%;
          margin: 0 auto;
          background: white;
          color: black;
        }

        .print-mode .print-layout-container {
          max-width: none;
          margin: 0;
          padding: 20px;
        }

        .print-header-section {
          margin-bottom: 2rem;
        }

        .print-main-content {
          min-height: 400px;
        }

        .print-footer-section {
          margin-top: 2rem;
        }

        @media print {
          .print-layout-container {
            background: white !important;
            color: black !important;
            box-shadow: none !important;
          }

          .print-header-section,
          .print-main-content,
          .print-footer-section {
            background: white !important;
            color: black !important;
          }

          /* Ensure proper page breaks */
          .print-main-content > * {
            page-break-inside: avoid;
          }

          /* Hide interactive elements */
          button,
          input,
          select,
          textarea,
          .interactive {
            display: none !important;
          }

          /* Ensure images and charts print properly */
          img,
          svg,
          canvas {
            max-width: 100% !important;
            height: auto !important;
          }

          /* Table printing */
          table {
            page-break-inside: avoid;
          }

          thead {
            display: table-header-group;
          }

          tr {
            page-break-inside: avoid;
            page-break-after: auto;
          }
        }
      `}</style>
    </div>
  );
};

export default PrintLayout;
