import type { ReleaseManifestArchive } from '../release-manifest-shape'

// Generated by scripts/build-release-manifest.ts. Do not edit manually.
import manifest_9baf2fd87e6e8f16997e015b9ba232f9975c401969353a86da9c6ee63d09b32e from './9baf2fd87e6e8f16997e015b9ba232f9975c401969353a86da9c6ee63d09b32e.json'
import manifest_b52cae617ffcff2f5316dc86536aa08a7d2dfc24b70b3c74ab8625c9f748f519 from './b52cae617ffcff2f5316dc86536aa08a7d2dfc24b70b3c74ab8625c9f748f519.json'

const ARCHIVED_RELEASE_MANIFESTS: Readonly<Record<string, ReleaseManifestArchive>> = Object.freeze({
  '9baf2fd87e6e8f16997e015b9ba232f9975c401969353a86da9c6ee63d09b32e': manifest_9baf2fd87e6e8f16997e015b9ba232f9975c401969353a86da9c6ee63d09b32e as ReleaseManifestArchive,
  'b52cae617ffcff2f5316dc86536aa08a7d2dfc24b70b3c74ab8625c9f748f519': manifest_b52cae617ffcff2f5316dc86536aa08a7d2dfc24b70b3c74ab8625c9f748f519 as ReleaseManifestArchive,
})

export function getArchivedReleaseManifest(hash: string): ReleaseManifestArchive | null {
  return ARCHIVED_RELEASE_MANIFESTS[hash] ?? null
}
