import type { ReleaseManifestArchive } from '../release-manifest-shape'

// Generated by scripts/build-release-manifest.ts. Do not edit manually.
import manifest_142de10232f403695592990b869a839d891287dbc1a7b8d007d57e364f898c57 from './142de10232f403695592990b869a839d891287dbc1a7b8d007d57e364f898c57.json'
import manifest_37f9c7a07cc4310686c5a7a2c7420f754403ae31fd5c67a700f374b010cddfb7 from './37f9c7a07cc4310686c5a7a2c7420f754403ae31fd5c67a700f374b010cddfb7.json'

const ARCHIVED_RELEASE_MANIFESTS: Readonly<Record<string, ReleaseManifestArchive>> = Object.freeze({
  '142de10232f403695592990b869a839d891287dbc1a7b8d007d57e364f898c57': manifest_142de10232f403695592990b869a839d891287dbc1a7b8d007d57e364f898c57 as ReleaseManifestArchive,
  '37f9c7a07cc4310686c5a7a2c7420f754403ae31fd5c67a700f374b010cddfb7': manifest_37f9c7a07cc4310686c5a7a2c7420f754403ae31fd5c67a700f374b010cddfb7 as ReleaseManifestArchive,
})

export function getArchivedReleaseManifest(hash: string): ReleaseManifestArchive | null {
  return ARCHIVED_RELEASE_MANIFESTS[hash] ?? null
}
