import type { ReleaseManifestArchive } from '../release-manifest-shape'

// Generated by scripts/build-release-manifest.ts. Do not edit manually.
import manifest_142de10232f403695592990b869a839d891287dbc1a7b8d007d57e364f898c57 from './142de10232f403695592990b869a839d891287dbc1a7b8d007d57e364f898c57.json'

const ARCHIVED_RELEASE_MANIFESTS: Readonly<Record<string, ReleaseManifestArchive>> = Object.freeze({
  '142de10232f403695592990b869a839d891287dbc1a7b8d007d57e364f898c57': manifest_142de10232f403695592990b869a839d891287dbc1a7b8d007d57e364f898c57 as ReleaseManifestArchive,
})

export function getArchivedReleaseManifest(hash: string): ReleaseManifestArchive | null {
  return ARCHIVED_RELEASE_MANIFESTS[hash] ?? null
}
